
package bomberman;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author David Benes
 */
public class ClientWindow extends javax.swing.JFrame implements ClientCallback {
    
    private final Client client;
    //private final ArrayList<Client> clients;
    
    /**
     * Map of pairs player ID number and placing number in window.
     */
    private final HashMap<Integer, Integer> ids;
    
    private final JLabel[] nameLabels;
    private final JPanel[] colorPanels;
    private final JLabel[] bootsLabels;
    private final JLabel[] bombTypeLabels;
    private final JLabel[] lifeLabels;
    private final JPanel[] playerPanels;
    
    private void runWindow() {
        client.registerCallback(this);
        client.start();
        
        /*for (Client client:clients) {
            client.registerCallback(this);
            client.start();
        }*/
        
        for (JPanel jp:playerPanels) {
            jp.setVisible(false);
        }
        jGraphicWidget.requestFocus();
    }
    
    /**
     * Creates new form ClientWindow
     * @param client
     */
    public ClientWindow(/*ArrayList<Client> clients*/Client client) {
        initComponents();
        this.nameLabels = new JLabel[]{jLabelP1Name, jLabelP2Name, jLabelP3Name, jLabelP4Name};
        this.colorPanels = new JPanel[]{jPanelP1Color, jPanelP2Color, jPanelP3Color, jPanelP4Color};
        this.bootsLabels = new JLabel[]{jLabelP1Boots, jLabelP2Boots, jLabelP3Boots, jLabelP4Boots};
        this.bombTypeLabels = new JLabel[]{jLabelP1BombType, jLabelP2BombType, jLabelP3BombType, jLabelP4BombType};
        this.lifeLabels = new JLabel[]{jLabelP1Lifes, jLabelP2Lifes, jLabelP3Lifes, jLabelP4Lifes};
        this.playerPanels = new JPanel[]{jPanelP1, jPanelP2, jPanelP3, jPanelP4};
        this.ids = new HashMap<>();
        this.client = client;
        //this.clients = clients;
        this.runWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanelP2 = new javax.swing.JPanel();
        jPanelP2Color = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelP2BombType = new javax.swing.JLabel();
        jLabelP2Lifes = new javax.swing.JLabel();
        jLabelP2Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelP2Boots = new javax.swing.JLabel();
        jPanelP3 = new javax.swing.JPanel();
        jPanelP3Color = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelP3BombType = new javax.swing.JLabel();
        jLabelP3Lifes = new javax.swing.JLabel();
        jLabelP3Name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelP3Boots = new javax.swing.JLabel();
        jPanelP4 = new javax.swing.JPanel();
        jPanelP4Color = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelP4BombType = new javax.swing.JLabel();
        jLabelP4Lifes = new javax.swing.JLabel();
        jLabelP4Name = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelP4Boots = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelConStat = new javax.swing.JLabel();
        jPanelP1 = new javax.swing.JPanel();
        jPanelP1Color = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelP1BombType = new javax.swing.JLabel();
        jLabelP1Lifes = new javax.swing.JLabel();
        jLabelP1Name = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelP1Boots = new javax.swing.JLabel();
        jGraphicWidget = new bomberman.GraphicWidget();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bomberman");
        setResizable(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanelP2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelP2Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelP2Color.setPreferredSize(new java.awt.Dimension(48, 48));
        jPanelP2Color.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelP2ColorLayout = new javax.swing.GroupLayout(jPanelP2Color);
        jPanelP2Color.setLayout(jPanelP2ColorLayout);
        jPanelP2ColorLayout.setHorizontalGroup(
            jPanelP2ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanelP2ColorLayout.setVerticalGroup(
            jPanelP2ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel2.setText("Bomb Type:");

        jLabel3.setText("Lifes:");

        jLabelP2BombType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP2BombType.setText("Basic");

        jLabelP2Lifes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP2Lifes.setText("3");

        jLabelP2Name.setText("Player2");

        jLabel1.setText("Bonus Boots:");

        jLabelP2Boots.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP2Boots.setText("No");

        javax.swing.GroupLayout jPanelP2Layout = new javax.swing.GroupLayout(jPanelP2);
        jPanelP2.setLayout(jPanelP2Layout);
        jPanelP2Layout.setHorizontalGroup(
            jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP2Layout.createSequentialGroup()
                        .addComponent(jPanelP2Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelP2BombType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP2Lifes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP2Boots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelP2Name))
                .addContainerGap())
        );
        jPanelP2Layout.setVerticalGroup(
            jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelP2Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP2Layout.createSequentialGroup()
                        .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelP2BombType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelP2Lifes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelP2Boots)))
                    .addComponent(jPanelP2Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelP3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelP3Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelP3Color.setPreferredSize(new java.awt.Dimension(48, 48));
        jPanelP3Color.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelP3ColorLayout = new javax.swing.GroupLayout(jPanelP3Color);
        jPanelP3Color.setLayout(jPanelP3ColorLayout);
        jPanelP3ColorLayout.setHorizontalGroup(
            jPanelP3ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanelP3ColorLayout.setVerticalGroup(
            jPanelP3ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel7.setText("Bomb Type:");

        jLabel8.setText("Lifes:");

        jLabelP3BombType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP3BombType.setText("Basic");

        jLabelP3Lifes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP3Lifes.setText("3");

        jLabelP3Name.setText("Player3");

        jLabel9.setText("Bonus Boots:");

        jLabelP3Boots.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP3Boots.setText("No");

        javax.swing.GroupLayout jPanelP3Layout = new javax.swing.GroupLayout(jPanelP3);
        jPanelP3.setLayout(jPanelP3Layout);
        jPanelP3Layout.setHorizontalGroup(
            jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP3Layout.createSequentialGroup()
                        .addComponent(jPanelP3Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelP3Layout.createSequentialGroup()
                                .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelP3BombType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelP3Lifes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(jPanelP3Layout.createSequentialGroup()
                                .addComponent(jLabelP3Boots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanelP3Layout.createSequentialGroup()
                        .addComponent(jLabelP3Name)
                        .addContainerGap())))
        );
        jPanelP3Layout.setVerticalGroup(
            jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelP3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelP3Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelP3Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelP3Layout.createSequentialGroup()
                        .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabelP3BombType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabelP3Lifes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabelP3Boots))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelP4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelP4Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelP4Color.setPreferredSize(new java.awt.Dimension(48, 48));
        jPanelP4Color.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelP4ColorLayout = new javax.swing.GroupLayout(jPanelP4Color);
        jPanelP4Color.setLayout(jPanelP4ColorLayout);
        jPanelP4ColorLayout.setHorizontalGroup(
            jPanelP4ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanelP4ColorLayout.setVerticalGroup(
            jPanelP4ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel18.setText("Bomb Type:");

        jLabel19.setText("Lifes:");

        jLabelP4BombType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP4BombType.setText("Basic");

        jLabelP4Lifes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP4Lifes.setText("3");

        jLabelP4Name.setText("Player4");

        jLabel12.setText("Bonus Boots:");

        jLabelP4Boots.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP4Boots.setText("No");

        javax.swing.GroupLayout jPanelP4Layout = new javax.swing.GroupLayout(jPanelP4);
        jPanelP4.setLayout(jPanelP4Layout);
        jPanelP4Layout.setHorizontalGroup(
            jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelP4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP4Layout.createSequentialGroup()
                        .addComponent(jPanelP4Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelP4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelP4BombType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelP4Layout.createSequentialGroup()
                                .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelP4Lifes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelP4Boots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabelP4Name))
                .addContainerGap())
        );
        jPanelP4Layout.setVerticalGroup(
            jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelP4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelP4Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP4Layout.createSequentialGroup()
                        .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabelP4BombType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabelP4Lifes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabelP4Boots)))
                    .addComponent(jPanelP4Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Connection status:");

        jLabelConStat.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelConStat.setText("No Connection");

        jPanelP1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelP1Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelP1Color.setPreferredSize(new java.awt.Dimension(48, 48));
        jPanelP1Color.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelP1ColorLayout = new javax.swing.GroupLayout(jPanelP1Color);
        jPanelP1Color.setLayout(jPanelP1ColorLayout);
        jPanelP1ColorLayout.setHorizontalGroup(
            jPanelP1ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanelP1ColorLayout.setVerticalGroup(
            jPanelP1ColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel4.setText("Bomb Type:");

        jLabel6.setText("Lifes:");

        jLabelP1BombType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP1BombType.setText("Basic");

        jLabelP1Lifes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP1Lifes.setText("3");

        jLabelP1Name.setText("Player1");

        jLabel10.setText("Bonus Boots:");

        jLabelP1Boots.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelP1Boots.setText("No");

        javax.swing.GroupLayout jPanelP1Layout = new javax.swing.GroupLayout(jPanelP1);
        jPanelP1.setLayout(jPanelP1Layout);
        jPanelP1Layout.setHorizontalGroup(
            jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP1Layout.createSequentialGroup()
                        .addComponent(jPanelP1Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelP1BombType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP1Lifes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP1Boots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelP1Name))
                .addContainerGap())
        );
        jPanelP1Layout.setVerticalGroup(
            jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelP1Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelP1Layout.createSequentialGroup()
                        .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelP1BombType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelP1Lifes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabelP1Boots)))
                    .addComponent(jPanelP1Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jGraphicWidget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jGraphicWidgetKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGraphicWidget, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConStat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGraphicWidget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jPanelP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabelConStat))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGraphicWidgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jGraphicWidgetKeyReleased
        try {
            switch (evt.getKeyCode()) {
                case KeyEvent.VK_UP:
                    //clients.get(0).move(Direction.UP);
                    client.move(Direction.UP);
                    break;
                case KeyEvent.VK_DOWN:
                    //clients.get(0).move(Direction.DOWN);
                    client.move(Direction.DOWN);
                    break;
                case KeyEvent.VK_RIGHT:
                    //clients.get(0).move(Direction.RIGHT);
                    client.move(Direction.RIGHT);
                    break;
                case KeyEvent.VK_LEFT:
                    //clients.get(0).move(Direction.LEFT);
                    client.move(Direction.LEFT);
                    break;
                case KeyEvent.VK_SPACE:
                    //clients.get(0).dropBomb();
                    client.dropBomb();
                    break;
                /*case KeyEvent.VK_W:
                    clients.get(1).move(Direction.UP);
                    break;*/
                default:
                    /*for (Client client:clients) {
                        client.sendBye();
                    }*/
                    client.sendBye();
            }
        } catch (IOException ex) {
            Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jGraphicWidgetKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bomberman.GraphicWidget jGraphicWidget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConStat;
    private javax.swing.JLabel jLabelP1BombType;
    private javax.swing.JLabel jLabelP1Boots;
    private javax.swing.JLabel jLabelP1Lifes;
    private javax.swing.JLabel jLabelP1Name;
    private javax.swing.JLabel jLabelP2BombType;
    private javax.swing.JLabel jLabelP2Boots;
    private javax.swing.JLabel jLabelP2Lifes;
    private javax.swing.JLabel jLabelP2Name;
    private javax.swing.JLabel jLabelP3BombType;
    private javax.swing.JLabel jLabelP3Boots;
    private javax.swing.JLabel jLabelP3Lifes;
    private javax.swing.JLabel jLabelP3Name;
    private javax.swing.JLabel jLabelP4BombType;
    private javax.swing.JLabel jLabelP4Boots;
    private javax.swing.JLabel jLabelP4Lifes;
    private javax.swing.JLabel jLabelP4Name;
    private javax.swing.JPanel jPanelP1;
    private javax.swing.JPanel jPanelP1Color;
    private javax.swing.JPanel jPanelP2;
    private javax.swing.JPanel jPanelP2Color;
    private javax.swing.JPanel jPanelP3;
    private javax.swing.JPanel jPanelP3Color;
    private javax.swing.JPanel jPanelP4;
    private javax.swing.JPanel jPanelP4Color;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateBonuses(HashMap<Integer, HashMap<BonusType, Boolean>> bonuses) {
        for (Integer id:bonuses.keySet()) {
            for (BonusType bt:bonuses.get(id).keySet()) {
                switch (bt) {
                    case BOOTS:
                        if (bonuses.get(id).get(bt)) bootsLabels[ids.get(id)].setText("Yes");
                        break;
                    case LARGEBOMB:
                        if (bonuses.get(id).get(bt)) bombTypeLabels[ids.get(id)].setText("Large");
                        break;
                }
            }
        }
    }
    
    @Override
    public void updateLifes(HashMap<Integer, Integer> lifes) {
        for (Integer id:lifes.keySet()) {
            lifeLabels[ids.get(id)].setText(lifes.get(id).toString());
        }
    }
    
    @Override
    public void updateMap(HashMap<Position, ArrayList<String>> map) {
        jGraphicWidget.updateMap(map);
    }

    @Override
    public void updateNames(HashMap<Integer, String> names) {
        for (Integer id:names.keySet()) {
            nameLabels[ids.get(id)].setText(names.get(id));
        }
    }

    @Override
    public void updateColors(HashMap<Integer, PlayerColor> colors) {
        for (Integer id:colors.keySet()) {
            colorPanels[ids.get(id)].setBackground(colors.get(id).toColor());
        }
    }

    @Override
    public void updateIDs(ArrayList<Integer> ids) {
        for (int i=0; i<ids.size(); i++) {
            this.ids.put(ids.get(i), i);
            playerPanels[i].setVisible(true);
        }
    }

    @Override
    public void setStatus(String status) {
        jLabelConStat.setText(status);
    }

    @Override
    public void gameOver(int winnerID) {
        if (winnerID != -1) playerPanels[ids.get(winnerID)].setBackground(Color.green);
        jGraphicWidget.setEnd(true);
    }

    @Override
    public void closeWindow() {
        this.dispose();
    }
}
